// Auth actions
export {
  type ApiKeyAuthenticator,
  type AuthenticateWithEmailParameters,
  type AuthenticateWithEmailReturnType,
  type AuthenticateWithOAuthParameters,
  type AuthenticateWithOAuthReturnType,
  authenticateWithEmail,
  authenticateWithOAuth,
  type EmailContact,
  type EmailCustomization,
  type GetAuthenticatorsParameters,
  type GetAuthenticatorsReturnType,
  type GetAuthProxyConfigIdReturnType,
  type GetOAuthLoginUrlParameters,
  type GetOAuthLoginUrlReturnType,
  type GetWhoamiParameters,
  type GetWhoamiReturnType,
  getAuthenticators,
  getAuthProxyConfigId,
  getOAuthLoginUrl,
  getWhoami,
  type LoginWithOTPParameters,
  type LoginWithOTPReturnType,
  loginWithOTP,
  type OAuthAuthenticator,
  type OtpContact,
  type PasskeyAuthenticator,
  type RegisterWithOTPParameters,
  type RegisterWithOTPReturnType,
  type RegisterWithPasskeyParameters,
  type RegisterWithPasskeyReturnType,
  registerWithOTP,
  registerWithPasskey,
} from './auth/index.js'

// Wallet actions
export {
  type GetUserWalletParameters,
  type GetUserWalletReturnType,
  getUserWallet,
  type Sign7702AuthorizationParameters,
  type Sign7702AuthorizationReturnType,
  type SignMessageParameters,
  type SignMessageReturnType,
  type SignTransactionParameters,
  type SignTransactionReturnType,
  type SignTypedDataV4Parameters,
  type SignTypedDataV4ReturnType,
  type SignUserOperationParameters,
  type SignUserOperationReturnType,
  sign7702Authorization,
  signMessage,
  signTransaction,
  signTypedDataV4,
  signUserOperation,
} from './wallet/index.js'
