// Auth actions
export {
  type AuthenticateWithEmailParameters,
  type AuthenticateWithEmailReturnType,
  type AuthenticateWithOAuthParameters,
  type AuthenticateWithOAuthReturnType,
  authenticateWithEmail,
  authenticateWithOAuth,
  type EmailCustomization,
  type GetAuthProxyConfigIdReturnType,
  type GetUserEmailParameters,
  type GetUserEmailReturnType,
  type GetWhoamiParameters,
  type GetWhoamiReturnType,
  getAuthProxyConfigId,
  getUserEmail,
  getWhoami,
  type LoginWithOTPParameters,
  type LoginWithOTPReturnType,
  loginWithOTP,
  type OtpContact,
  type RegisterWithOTPParameters,
  type RegisterWithOTPReturnType,
  type RegisterWithPasskeyParameters,
  type RegisterWithPasskeyReturnType,
  registerWithOTP,
  registerWithPasskey,
} from './auth/index.js'

// Wallet actions
export {
  type GetUserWalletParameters,
  type GetUserWalletReturnType,
  getUserWallet,
  type Sign7702AuthorizationParameters,
  type Sign7702AuthorizationReturnType,
  type SignMessageParameters,
  type SignMessageReturnType,
  type SignTransactionParameters,
  type SignTransactionReturnType,
  type SignTypedDataV4Parameters,
  type SignTypedDataV4ReturnType,
  type SignUserOperationParameters,
  type SignUserOperationReturnType,
  sign7702Authorization,
  signMessage,
  signTransaction,
  signTypedDataV4,
  signUserOperation,
} from './wallet/index.js'
