#!/usr/bin/env node
/**
 * API surface reports for publishable packages (review playbook, Step 2).
 *
 * Writes one `docs/api-reports/<unscoped-name>.api.md` per package, listing
 * every public export (name, kind, and a truncated type signature) from the
 * package's built type entry. Any public-API change then shows up in review
 * as a diff to a single file — and CI fails when the report is stale.
 *
 *   node scripts/api-report.mjs          # regenerate reports
 *   node scripts/api-report.mjs --check  # exit 1 if reports are stale
 *
 * Requires `pnpm build` first (reads dist type entries).
 */
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import ts from 'typescript'

const ROOT = path.resolve(import.meta.dirname, '..')
const OUT_DIR = path.join(ROOT, 'docs', 'api-reports')
const CHECK = process.argv.includes('--check')

// Same source of truth the packaging smoke test uses.
const pkgDirs = execFileSync('node', ['scripts/check-publishable.mjs', '--list'], {
  cwd: ROOT,
  encoding: 'utf8',
})
  .trim()
  .split('\n')
  .filter(Boolean)

/** Max characters of type text per export — enough to see shape changes
 * without letting one mega-type swamp the report. */
const TYPE_TEXT_LIMIT = 300

function typeEntry(pkgDir) {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, pkgDir, 'package.json'), 'utf8'))
  const entry = pkg.exports?.['.']?.types ?? pkg.types
  if (!entry) return null
  return { name: pkg.name, file: path.join(ROOT, pkgDir, entry) }
}

function reportFor(entryFile) {
  const program = ts.createProgram([entryFile], {
    target: ts.ScriptTarget.ESNext,
    module: ts.ModuleKind.ESNext,
    // Built d.ts files import with `.js` specifiers; Bundler resolution maps
    // them onto the sibling `.d.ts` files so re-exports resolve.
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    skipLibCheck: true,
  })
  const checker = program.getTypeChecker()
  const source = program.getSourceFile(entryFile)
  const moduleSymbol = checker.getSymbolAtLocation(source)
  if (!moduleSymbol) return []

  const lines = []
  for (const symbol of checker.getExportsOfModule(moduleSymbol)) {
    const resolved =
      symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol
    const decl = resolved.declarations?.[0]
    const kind = decl ? ts.SyntaxKind[decl.kind].replace(/Declaration$/, '') : 'Unknown'
    let typeText = ''
    try {
      const type = checker.getTypeOfSymbolAtLocation(resolved, decl ?? source)
      typeText = checker.typeToString(
        type,
        undefined,
        ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.WriteArrowStyleSignature,
      )
    } catch {
      typeText = '(unresolved)'
    }
    if (typeText.length > TYPE_TEXT_LIMIT) typeText = `${typeText.slice(0, TYPE_TEXT_LIMIT)}…`
    // Type-only exports (interfaces, type aliases) stringify as their own
    // name, which carries no information — record just name + kind for those.
    const entry =
      typeText === symbol.name || typeText === 'any'
        ? `- \`${symbol.name}\` — ${kind}`
        : `- \`${symbol.name}\` — ${kind}: \`${typeText}\``
    lines.push(entry)
  }
  return lines.sort((a, b) => a.localeCompare(b))
}

let stale = []
fs.mkdirSync(OUT_DIR, { recursive: true })

for (const dir of pkgDirs) {
  const entry = typeEntry(dir)
  if (!entry) continue
  if (!fs.existsSync(entry.file)) {
    console.error(`skip ${entry.name}: ${entry.file} missing — run \`pnpm build\` first`)
    process.exitCode = 1
    continue
  }
  const body = [
    `# API report: ${entry.name}`,
    '',
    '<!-- Generated by scripts/api-report.mjs — do not edit by hand.',
    '     Regenerate with: pnpm build && node scripts/api-report.mjs -->',
    '',
    ...reportFor(entry.file),
    '',
  ].join('\n')

  const outFile = path.join(OUT_DIR, `${entry.name.split('/').pop()}.api.md`)
  const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, 'utf8') : ''
  if (CHECK) {
    if (current !== body) stale.push(path.relative(ROOT, outFile))
  } else if (current !== body) {
    fs.writeFileSync(outFile, body)
    console.log(`updated ${path.relative(ROOT, outFile)}`)
  }
}

if (CHECK && stale.length) {
  console.error(
    `Stale API report(s): ${stale.join(', ')}\n` +
      'The public API surface changed. Regenerate with:\n' +
      '  pnpm build && node scripts/api-report.mjs\n' +
      'and include the updated report (plus a changeset) in this PR.',
  )
  process.exit(1)
}
if (CHECK) console.log('API reports are up to date.')
